import {
  mdiAccountCircleOutline,
  mdiAccount,
  mdiText,
  mdiEarth,
  mdiBookmarkCheck,
  mdiBookshelf,
  mdiBroadcast,
  mdiCellphone,
  mdiAccountGroup,
  mdiClose,
  mdiArrowCollapseHorizontal,
  mdiArrowCollapseUp,
  mdiCommentTextMultiple,
  mdiViewDashboard,
  mdiDeleteForever,
  mdiDoor,
  mdiDotsHorizontal,
  mdiChevronDown,
  mdiPencil,
  mdiEmailEditOutline,
  mdiEmail,
  mdiArrowExpandHorizontal,
  mdiLightbulbOn,
  mdiMessageAlertOutline,
  mdiNewspaperVariant,
  mdiFlag,
  mdiGithub,
  mdiAt,
  mdiHelpCircleOutline,
  mdiLifebuoy,
  mdiHistory,
  mdiCompass,
  mdiHome,
  mdiTranslate,
  mdiInformationOutline,
  mdiGamepadVariant,
  mdiChevronLeft,
  mdiLinkedin,
  mdiLink,
  mdiLockOutline,
  mdiDotsVertical,
  mdiMessageTextLock,
  mdiDotsHorizontalCircleOutline,
  mdiBellSleep,
  mdiBell,
  mdiOpenInNew,
  mdiKey,
  mdiLock,
  mdiAccountCircle,
  mdiEmoticonHappyOutline,
  mdiRefresh,
  mdiReply,
  mdiChevronRight,
  mdiMagnify,
  mdiCogOutline,
  mdiShareAll,
  mdiForum,
  mdiShieldCheck,
  mdiHomeCity,
  mdiBookmarkPlusOutline,
  mdiTransferRight,
  mdiTwitter,
  mdiChevronUp,
  mdiArrowUpBold,
  mdiArrowUpBoldOutline,
  mdiLockClock,
  mdiWeb,
} from '@mdi/js';

export const iconMap: Record<string, string> = {
  AccountCircleOutline: mdiAccountCircleOutline,
  Account: mdiAccount,
  Answer: mdiText,
  AnyoneVisibility: mdiEarth,
  Bookmarked: mdiBookmarkCheck,
  Bookshelf: mdiBookshelf,
  Broadcast: mdiBroadcast,
  Cellphone: mdiCellphone,
  Channel: mdiAccountGroup,
  Close: mdiClose,
  CollapseHorizontal: mdiArrowCollapseHorizontal,
  CollapseUp: mdiArrowCollapseUp,
  Comments: mdiCommentTextMultiple,
  Dashboard: mdiViewDashboard,
  Delete: mdiDeleteForever,
  Door: mdiDoor,
  Dots: mdiDotsHorizontal,
  Down: mdiChevronDown,
  Edit: mdiPencil,
  EmailEditOutline: mdiEmailEditOutline,
  Email: mdiEmail,
  ExpandHorizontal: mdiArrowExpandHorizontal,
  Explore: mdiLightbulbOn,
  Feedback: mdiMessageAlertOutline,
  Feed: mdiNewspaperVariant,
  Flag: mdiFlag,
  Github: mdiGithub,
  Handle: mdiAt,
  HelpCircleOutline: mdiHelpCircleOutline,
  Help: mdiLifebuoy,
  History: mdiHistory,
  HomeFab: mdiCompass,
  Home: mdiHome,
  I18n: mdiTranslate,
  Info: mdiInformationOutline,
  JoinChafan: mdiGamepadVariant,
  Left: mdiChevronLeft,
  Linkedin: mdiLinkedin,
  Link: mdiLink,
  LockOutline: mdiLockOutline,
  Logout: mdiClose,
  Menu: mdiDotsVertical,
  MessageTextLock: mdiMessageTextLock,
  More: mdiDotsHorizontalCircleOutline,
  MuteNotification: mdiBellSleep,
  Notification: mdiBell,
  OpenInNew: mdiOpenInNew,
  Password: mdiKey,
  PrivateSite: mdiLock,
  Profile: mdiAccountCircle,
  Reaction: mdiEmoticonHappyOutline,
  Refresh: mdiRefresh,
  RegisteredUserOnly: mdiLock,
  RegisteredVisibility: mdiAccountGroup,
  Reply: mdiReply,
  Right: mdiChevronRight,
  Search: mdiMagnify,
  Settings: mdiCogOutline,
  Share: mdiShareAll,
  Sharing: mdiForum,
  ShieldCheck: mdiShieldCheck,
  Site: mdiHomeCity,
  ToBookmark: mdiBookmarkPlusOutline,
  Transfer: mdiTransferRight,
  Twitter: mdiTwitter,
  Up: mdiChevronUp,
  Upvoted: mdiArrowUpBold,
  Upvote: mdiArrowUpBoldOutline,
  VerifyCode: mdiLockClock,
  Web: mdiWeb,
};
